# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - erapulus-client-web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.2'

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      - name: Build application
        run: npm run build-prod

      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npm run e2e

      - name: Upload management-panel app artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: management-panel-app
          path: ./dist/apps/admin-panel/*


  deploy-admin-panel:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: management-panel-app

      - name: 'Deploy Management Panel to Azure Web App'
        id: deploy-management-panel-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'erapulus-client-web'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FEE8B314406542858A39140CEE8BCFB8 }}
          package: .
